version: "3.7"

services:

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "nyaone"
      POSTGRES_PASSWORD: "join+nya.1"
      POSTGRES_DB: "join"
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    ports:
      - 127.0.0.1:5432:5432

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
