version: "3.7"

services:

  app:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - internal_network
      - external_network
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./config.yml:/app/config.yml:ro"

  db:
    image: postgres:15-alpine
    restart: always
    networks:
      - internal_network
    environment:
      POSTGRES_USER: "nyaone"
      POSTGRES_PASSWORD: "join+nya.1"
      POSTGRES_DB: "join"
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - "./db:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal_network
    volumes:
      - "./redis:/data"

networks:
  internal_network:
    internal: true
  external_network:
